services:
  mqtt:
    image: eclipse-mosquitto:2.0
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs
      - ./mosquitto/config:/mosquitto/config
